### ISSUE TITLE
Change Swipe Detection to ViewPager

### ISSUE THREAD

**Issue by snug** [light-launcher/Light-Android-Launcher#39] opened 2018-12-12 03:43 UTC
Use ViewPager to ensure a smooth swiping experience on all devices.

https://developer.android.com/reference/android/support/v4/view/ViewPager
https://developer.android.com/training/animation/screen-slide

**Comment by postapczuk** [comment] 2018-12-12 09:35
ViewPager was added in API 22 - the current (version 1.4) swipe logic works already with this one.

**Comment by jancborchardt** [comment] 2018-12-12 13:08
Didn’t test the new master yet, but if it’s not using ViewPager, then this is a duplicate of https://github.com/postapczuk/Light-Android-Launcher/issues/11 ?

cc @postapczuk

**Comment by postapczuk** [comment] 2018-12-13 20:11
Yep didn't have much time for view pager. It's done by animation way, and works from API 17. I think it's good that there is a new task for it. The old one had too much off top.

**Comment by postapczuk** [comment] 2019-03-11 13:25
I've solved it different way: https://github.com/light-launcher/Light-Android-Launcher/pull/55

**Closed** 2019-03-13 22:02 UTC
Labels: design, enhancement
